# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/database_compendium',
                'doc_host': 'https://Autonomy-Data-Unit.github.io',
                'git_url': 'https://github.com/Autonomy-Data-Unit/database_compendium',
                'lib_path': 'database_compendium'},
  'syms': { 'database_compendium.core': { 'database_compendium.core.get_qualityOutcomes_uniqueColumnValues': ( 'nhs_quality&outcomes_scrapers.html#get_qualityoutcomes_uniquecolumnvalues',
                                                                                                               'database_compendium/core.py')}}}
